# Primeiros Playbooks

- name: Primeiro playbook para coleta de informações
  hosts: all
  gather_facts: no
  tasks:

    - name: Coletar comando "show version"
      ansible.netcommon.cli_command:
        command: show version
      register: cmd_version

    - name: Coletar o comando "show ip interface brief"
      ansible.netcommon.cli_command:
        command: show ip int brief
      register: cmd_intf

    - name: Exibir versão do IOS
      debug:
        var: cmd_version.stdout_lines

    - name: Exibir informações de Interfaces
      debug:
        var: cmd_intf.stdout_lines
